### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-1l21q#5]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Vishal-K-988** [comment]
![Screenshot 2022-08-07 004729](https://user-images.githubusercontent.com/93390689/183263157-83e693e5-60ee-4395-ab9b-5c2c1799f769.jpg)
I have updated the path but it's not showing

**Comment by vishalkumargeed** [comment]
Done this quest 
![Screenshot 2022-08-07 145958](https://user-images.githubusercontent.com/93390689/183284716-ae5ccc93-1038-4b39-8337-a74a71f86f41.jpg)

**Comment by vishalkumargeed** [comment]
resolved the issue
